version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
    registries:
      - github-npm
registries:
  github-npm:
    type: "npm-registry"
    url: "https://npm.pkg.github.com"
    token: "${{secrets.NPM_TOKEN_GITHUB}}"
