version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - github-npm
registries:
  github-npm:
    type: "npm-registry"
    url: "https://npm.pkg.github.com"
    token: "${{secrets.GH_NPM_TOKEN}}"
    replaces-base: true
